// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDESG8t2_C06MOYdUWSe-Q_ZigO08SPbfQ',
    appId: '1:859478353438:web:2eca59fd72684c1163300f',
    messagingSenderId: '859478353438',
    projectId: 'uas-23312065-b9c3e',
    authDomain: 'uas-23312065-b9c3e.firebaseapp.com',
    storageBucket: 'uas-23312065-b9c3e.firebasestorage.app',
    measurementId: 'G-CRHEM946NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5Qmdw9Iwne1Hc3moph6vJp-mFNb2JNg',
    appId: '1:859478353438:android:c75ac4d99d8d3ebc63300f',
    messagingSenderId: '859478353438',
    projectId: 'uas-23312065-b9c3e',
    storageBucket: 'uas-23312065-b9c3e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDESG8t2_C06MOYdUWSe-Q_ZigO08SPbfQ',
    appId: '1:859478353438:web:94723df34b9fe82963300f',
    messagingSenderId: '859478353438',
    projectId: 'uas-23312065-b9c3e',
    authDomain: 'uas-23312065-b9c3e.firebaseapp.com',
    storageBucket: 'uas-23312065-b9c3e.firebasestorage.app',
    measurementId: 'G-QZZRW8D71L',
  );
}
